version: '3.8'

services:
  localstack:
    container_name: "${LOCALSTACK_HOST:-localstack_main}"
    image: localstack/localstack:3.4.0
    ports:
      - "127.0.0.1:4510-4559:4510-4559"  # external service port range
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
    environment:
      - DEBUG=${DEBUG:-0}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./localstack/volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
